language: go

os:
  - linux
  - osx

dist: bionic

go:
  - 1.12.x
  - 1.x

env:
  global:
    - GO111MODULE=on
  jobs:
    - GOTESTFLAGS=""
    - GOTESTFLAGS="-race"

jobs:
  exclude:
    - os: osx
      go: 1.12.x

install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y g++ pkg-config scons ragel gengetopt libuv1-dev libunwind-dev libpulse-dev libsox-dev libcpputest-dev libtool intltool autoconf automake make cmake; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew unlink python@2 && brew list | grep -vE 'pkg-config|automake|libtool|cmake|xz|readline|openssl|sqlite|python' | xargs brew pin && brew install scons ragel gengetopt libuv speexdsp sox cpputest; fi
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.27.0
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

before_script:
  - git clone https://github.com/roc-streaming/roc-toolkit.git /tmp/roc
  - scons -C /tmp/roc -Q --build-3rdparty=openfec
  - sudo scons -C /tmp/roc -Q --build-3rdparty=openfec install

script:
  - cd roc
  - go get -v .
  - go test ${GOTESTFLAGS} -coverprofile profile.cov
  - ${GOPATH}/bin/golangci-lint run .
  - if [ "$TRAVIS_REPO_SLUG" = "roc-streaming/roc-go" ]; then ${GOPATH}/bin/goveralls -coverprofile profile.cov -service=travis-ci; fi
